### ISSUE TITLE
dog attacking owner of k9 if firing with weapon

### ISSUE THREAD

**Issue by sadoj-kuro** [Mathu-lmn/mth-K9#1]
when i firing with weapon with config_select to false, the k9 attacking me.

**Comment by Mathu-lmn** [comment]
oh, that's weird, i'll add a check so he won't attack the owner, thanks !

**Comment by Mathu-lmn** [comment]
fixed, please update the resource !

**Comment by sadoj-kuro** [comment]
sorry i reopen the issue, i have tested and sometimes the dog attacks me sometimes not

**Comment by sadoj-kuro** [comment]
ok i have find why

you need to add a relation group first

AddRelationshipGroup

after that you need to assign dog and player in this group with

SetPedRelationshipGroupHash

after that the dog and player is in the same groupe and won't attack

**Comment by Mathu-lmn** [comment]
but group leader and members fixed it for me :/

**Comment by sadoj-kuro** [comment]
wierd, maybe i need to add this for me because of my home script for manage relationship between ped and player
