### ISSUE TITLE
V 1.1.0

### ISSUE THREAD

**Issue by Mathu-lmn** [Mathu-lmn/mth-K9#2]
- [x] Create the ped server side to avoid anti cheats to detect client ped creation
- [x] Don't give the script the entity control
- [x] Create utils.lua with shownotification and other utils
- [x] Remove STRING entry for blip
- [x] Fix the exit function that sometimes does not works
- [x] Fix dog death detection
- [x] Fix dog not responding after player death

**Comment by sadoj-kuro** [comment]
switch the current RageUi for Dylan MALANDAIN, Kalyptus its better https://github.com/ImBaphomettt/RageUI
